item:
  material: 'BLAZE_ROD'
  display-name: '&5SaveRod'
  lore: '&2The one and only!'
keep-levels: true

messages:
  give-yourself: '&5You gave yourself a Saverod'
  give-other: '&4You gave someone else a SaveRod'
  received: '&5You received a SaveRod'
  items-saved: '&2Your items were saved by the powers of the &6SaveRod'